//! Heuristic detection of auto-generated files from path patterns.
//!
//! Bug-fix attribution propagates badly through generated files: a
//! "fix(schema): add field" commit will touch the .proto/.graphql source
//! AND the generated .pb.go/.ts bindings, so the bindings end up with a
//! bug_fix_changes count even though they are mechanical artifacts of
//! the schema fix. The bindings then float to the top of bugspots
//! queries, drowning out actually-broken code.
//!
//! This module classifies a file as generated based on path patterns
//! that strongly indicate machine-authored content. The data is still
//! collected (changes, coupling, authors) so co-change graphs remain
//! useful, but `is_generated_path()` callers can choose to suppress
//! bug-fix attribution and filter generated files out of "what is
//! broken?" queries.
//!
//! # Scope
//!
//! Path-based only. Header-marker detection (`@generated`,
//! `// Code generated by ... DO NOT EDIT.`) and `.gitattributes`
//! `linguist-generated=true` parsing are intentionally out of scope
//! here - they require file-content reads that the aggregator does
//! not currently perform. They can be layered on top later.
//!
//! # False-negative bias
//!
//! Patterns are conservative: when in doubt we treat a file as
//! human-authored. The cost of a false negative (one extra bugspots
//! row) is much lower than the cost of a false positive (silently
//! losing bug signal on a real source file).

use std::sync::OnceLock;

use regex::RegexSet;

/// Path-component names that mean "this directory holds generated
/// output." Matched component-wise (so `regenerate_token.rs` and
/// `degenerate_input.rs` do not collide with `generated`), which also
/// means top-level directories like `generated/types.rs` register
/// correctly - the original substring scan with leading slashes
/// silently missed those.
const GENERATED_DIR_COMPONENTS: &[&str] = &[
    "generated",
    "__generated__",
    ".generated",
    "autogenerated",
    "auto-generated",
    "codegen",
    "grpc-gen",
    "grpc_gen",
];

/// Filenames that are essentially always generated. Matched on the
/// basename only.
const GENERATED_BASENAMES: &[&str] = &[
    "generated.rs",
    "generated.go",
    "generated.ts",
    "generated.js",
    "generated.py",
    "schema.generated.ts",
    "schema.generated.graphql",
    "graphql.schema.generated.ts",
];

/// `RegexSet` over filename-shape generated artifacts. A single set
/// scan beats a per-pattern `is_match` loop because the regex engine
/// can build a unified DFA.
fn generated_basename_set() -> &'static RegexSet {
    static CELL: OnceLock<RegexSet> = OnceLock::new();
    CELL.get_or_init(|| {
        RegexSet::new([
            // Protobuf and gRPC bindings
            r"\.pb\.go$",
            r"\.pb\.cc$",
            r"\.pb\.h$",
            r"_pb\.py$",
            r"_pb2\.py$",
            r"_pb2_grpc\.py$",
            r"\.pb\.ts$",
            r"\.pb\.js$",
            r"_grpc\.pb\.go$",
            // Type bindings
            r"\.d\.ts$",
            // GraphQL codegen
            r"\.generated\.[a-z]+$",
            // OpenAPI / swagger codegen
            r"\.openapi\.(ts|js|go)$",
            r"\.swagger\.(ts|js|go)$",
            // Common machine-translation output
            r"\.min\.map$",
            // Snapshot test artifacts (not generated source per se but
            // similar bug-attribution problem: snapshot updates are
            // mechanical, not bug fixes).
            r"\.snap$",
        ])
        .expect("static regex set compiles")
    })
}

/// Returns `true` if the path looks like an auto-generated file.
///
/// Uses path patterns only; never reads file contents.
pub fn is_generated_path(path: &str) -> bool {
    if path.is_empty() {
        return false;
    }
    let normalized = path.replace('\\', "/");

    // Component-wise directory check. This handles repo-root paths
    // (`generated/types.rs`) correctly while still rejecting
    // `regenerate_token.rs` / `degenerate_input.rs` (substring matches
    // that are not standalone components).
    for component in normalized.split('/') {
        if GENERATED_DIR_COMPONENTS.contains(&component) {
            return true;
        }
    }

    let basename = normalized.rsplit('/').next().unwrap_or(normalized.as_str());

    if GENERATED_BASENAMES.contains(&basename) {
        return true;
    }

    generated_basename_set().is_match(basename)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn directory_markers_hit() {
        assert!(is_generated_path("src/generated/types.rs"));
        assert!(is_generated_path("packages/api/__generated__/index.ts"));
        assert!(is_generated_path("crates/agnix-rules/.generated/data.rs"));
        assert!(is_generated_path("internal/codegen/handlers.go"));
        assert!(is_generated_path("api/grpc-gen/service_pb.go"));
    }

    #[test]
    fn top_level_generated_directories_hit() {
        // Reviewer-caught bug: the previous substring scan with leading
        // slashes silently missed top-level directories because git
        // paths are repo-root-relative with no leading slash.
        assert!(is_generated_path("generated/types.rs"));
        assert!(is_generated_path("__generated__/index.ts"));
        assert!(is_generated_path("codegen/handlers.go"));
        assert!(is_generated_path("autogenerated/foo.rs"));
        assert!(is_generated_path("auto-generated/foo.rs"));
    }

    #[test]
    fn protobuf_grpc_basenames_hit() {
        assert!(is_generated_path("api/v1/user.pb.go"));
        assert!(is_generated_path("api/v1/user_grpc.pb.go"));
        assert!(is_generated_path("api/v1/user.pb.cc"));
        assert!(is_generated_path("api/v1/user.pb.h"));
        assert!(is_generated_path("python/api_pb2.py"));
        assert!(is_generated_path("python/api_pb2_grpc.py"));
        assert!(is_generated_path("ts/api.pb.ts"));
    }

    #[test]
    fn type_bindings_hit() {
        assert!(is_generated_path("dist/index.d.ts"));
        assert!(is_generated_path("packages/api/types/user.d.ts"));
    }

    #[test]
    fn dotted_generated_extensions_hit() {
        assert!(is_generated_path("schema.generated.ts"));
        assert!(is_generated_path("api/queries.generated.graphql"));
        assert!(is_generated_path("client.openapi.ts"));
        assert!(is_generated_path("client.swagger.go"));
    }

    #[test]
    fn snapshot_files_hit() {
        // Snapshots aren't strictly generated source but they share the
        // same bug-attribution problem (mechanical updates).
        assert!(is_generated_path("__snapshots__/test.js.snap"));
    }

    #[test]
    fn windows_path_separator_works() {
        assert!(is_generated_path(r"src\generated\types.rs"));
        assert!(is_generated_path(r"api\v1\user.pb.go"));
    }

    #[test]
    fn human_authored_paths_skip() {
        assert!(!is_generated_path("src/main.rs"));
        assert!(!is_generated_path("src/auth/login.ts"));
        assert!(!is_generated_path("README.md"));
        assert!(!is_generated_path("Cargo.toml"));
        assert!(!is_generated_path("docs/architecture.md"));
        // "regenerate" and "degenerate" are common words in human code,
        // make sure we don't match the substring.
        assert!(!is_generated_path("src/regenerate_token.rs"));
        assert!(!is_generated_path("tests/degenerate_input.rs"));
    }

    #[test]
    fn empty_path_is_not_generated() {
        assert!(!is_generated_path(""));
    }
}
